"""
google_drive.py — Google Drive read/write tool

Invocation contract
-------------------
invocation["tool_name"]  = "google_drive"
invocation["action"]     = "read" | "write" | "list" | "search"
invocation["input"]      = {
    # read
    "file_id":    str,   # Google Drive file ID

    # write
    "name":       str,   # file name
    "content":    str,   # text content to write
    "folder_id":  str,   # optional parent folder ID
    "mime_type":  str,   # optional, default "text/plain"

    # list
    "folder_id":  str,   # folder to list (optional, defaults to root)
    "page_size":  int,   # optional, default 20

    # search
    "query":      str,   # search query (Drive query syntax or plain text)
    "page_size":  int,   # optional, default 10
}

Env vars
--------
GOOGLE_DRIVE_TOKEN_JSON — path to OAuth2 token file generated by the auth flow
                          (run the one-time auth script to generate this)

Setup
-----
1. Create a project at console.cloud.google.com
2. Enable the Google Drive API
3. Create OAuth2 Desktop credentials, download oauth_client.json
4. Run the one-time auth flow to generate drive_token.json
5. Set GOOGLE_DRIVE_TOKEN_JSON=/path/to/drive_token.json in .env
"""
from __future__ import annotations

import io
import json
import logging
import os
from typing import Any

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("tool_server.tools.google_drive")

_TOKEN_PATH: str = os.getenv("GOOGLE_DRIVE_TOKEN_JSON", "").strip()
_SCOPES = ["https://www.googleapis.com/auth/drive"]


def _get_service():
    """Build and return an authenticated Drive service using OAuth2 token."""
    from google.oauth2.credentials import Credentials
    from googleapiclient.discovery import build

    if not _TOKEN_PATH:
        raise ValueError(
            "GOOGLE_DRIVE_TOKEN_JSON is not set. "
            "Run the one-time auth flow to generate a token file."
        )
    if not os.path.exists(_TOKEN_PATH):
        raise FileNotFoundError(
            f"Drive token not found at: {_TOKEN_PATH}"
        )

    creds = Credentials.from_authorized_user_file(_TOKEN_PATH, _SCOPES)
    return build("drive", "v3", credentials=creds, cache_discovery=False)


async def run(invocation: dict[str, Any]) -> dict[str, Any]:
    action: str = str(invocation.get("action", "")).strip().lower()
    params: dict[str, Any] = invocation.get("input", {}) or {}

    try:
        service = _get_service()
    except (ValueError, FileNotFoundError) as exc:
        return {"status": "failed", "output": {}, "error": str(exc)}
    except Exception as exc:
        return {"status": "failed", "output": {}, "error": f"Auth error: {exc}"}

    if action == "read":
        return await _read(service, params)
    elif action == "write":
        return await _write(service, params)
    elif action == "list":
        return await _list(service, params)
    elif action == "search":
        return await _search(service, params)
    else:
        return {
            "status": "failed",
            "output": {},
            "error": f"Unknown action '{action}'. Use: read, write, list, search",
        }


async def _read(service, params: dict) -> dict:
    file_id: str = str(params.get("file_id", "")).strip()
    if not file_id:
        return {"status": "failed", "output": {}, "error": "read requires input.file_id"}

    try:
        # Get file metadata
        meta = service.files().get(fileId=file_id, fields="id,name,mimeType,size").execute()
        mime = meta.get("mimeType", "")

        # Export Google Docs/Sheets/Slides as plain text
        if mime == "application/vnd.google-apps.document":
            content_bytes = service.files().export(
                fileId=file_id, mimeType="text/plain"
            ).execute()
        elif mime == "application/vnd.google-apps.spreadsheet":
            content_bytes = service.files().export(
                fileId=file_id, mimeType="text/csv"
            ).execute()
        elif mime.startswith("text/") or mime == "application/json":
            request = service.files().get_media(fileId=file_id)
            from googleapiclient.http import MediaIoBaseDownload
            buf = io.BytesIO()
            downloader = MediaIoBaseDownload(buf, request)
            done = False
            while not done:
                _, done = downloader.next_chunk()
            content_bytes = buf.getvalue()
        else:
            return {
                "status": "failed",
                "output": {},
                "error": f"Cannot read binary file type: {mime}. Only text/document types are supported.",
            }

        content = content_bytes.decode("utf-8", errors="replace") if isinstance(content_bytes, bytes) else str(content_bytes)
        logger.info("Drive read: file_id=%s name=%s len=%d", file_id, meta.get("name"), len(content))

        return {
            "status": "succeeded",
            "output": {
                "file_id": file_id,
                "name": meta.get("name", ""),
                "mime_type": mime,
                "content": content,
            },
            "error": "",
        }

    except Exception as exc:
        return {"status": "failed", "output": {}, "error": f"Drive read error: {exc}"}


async def _write(service, params: dict) -> dict:
    name: str = str(params.get("name", "")).strip()
    content: str = str(params.get("content", ""))
    folder_id: str = str(params.get("folder_id", "")).strip()
    mime_type: str = str(params.get("mime_type", "text/plain")).strip()

    if not name:
        return {"status": "failed", "output": {}, "error": "write requires input.name"}

    try:
        from googleapiclient.http import MediaInMemoryUpload

        metadata: dict[str, Any] = {"name": name}
        if folder_id:
            metadata["parents"] = [folder_id]

        media = MediaInMemoryUpload(content.encode("utf-8"), mimetype=mime_type)

        # Check if file with same name already exists in folder
        query = f"name = '{name}' and trashed = false"
        if folder_id:
            query += f" and '{folder_id}' in parents"

        existing = service.files().list(q=query, fields="files(id,name)").execute()
        files = existing.get("files", [])

        if files:
            # Update existing file
            file_id = files[0]["id"]
            result = service.files().update(
                fileId=file_id,
                body={"name": name},
                media_body=media,
                fields="id,name,webViewLink",
            ).execute()
            action_taken = "updated"
        else:
            # Create new file
            result = service.files().create(
                body=metadata,
                media_body=media,
                fields="id,name,webViewLink",
            ).execute()
            action_taken = "created"

        logger.info("Drive write: %s file_id=%s name=%s", action_taken, result.get("id"), name)

        return {
            "status": "succeeded",
            "output": {
                "file_id": result.get("id", ""),
                "name": result.get("name", ""),
                "web_link": result.get("webViewLink", ""),
                "action": action_taken,
            },
            "error": "",
        }

    except Exception as exc:
        return {"status": "failed", "output": {}, "error": f"Drive write error: {exc}"}


async def _list(service, params: dict) -> dict:
    folder_id: str = str(params.get("folder_id", "root")).strip() or "root"
    page_size: int = int(params.get("page_size", 20))

    try:
        query = f"'{folder_id}' in parents and trashed = false"
        result = service.files().list(
            q=query,
            pageSize=min(page_size, 100),
            fields="files(id,name,mimeType,size,modifiedTime,webViewLink)",
        ).execute()

        files = result.get("files", [])
        logger.info("Drive list: folder=%s found=%d", folder_id, len(files))

        return {
            "status": "succeeded",
            "output": {
                "folder_id": folder_id,
                "count": len(files),
                "files": files,
            },
            "error": "",
        }

    except Exception as exc:
        return {"status": "failed", "output": {}, "error": f"Drive list error: {exc}"}


async def _search(service, params: dict) -> dict:
    query: str = str(params.get("query", "")).strip()
    page_size: int = int(params.get("page_size", 10))

    if not query:
        return {"status": "failed", "output": {}, "error": "search requires input.query"}

    try:
        # Support plain text search (wrap in fullText contains) or raw Drive query syntax
        if "contains" in query or "=" in query or "in parents" in query:
            drive_query = query  # raw Drive query syntax
        else:
            drive_query = f"fullText contains '{query}' and trashed = false"

        result = service.files().list(
            q=drive_query,
            pageSize=min(page_size, 100),
            fields="files(id,name,mimeType,size,modifiedTime,webViewLink)",
        ).execute()

        files = result.get("files", [])
        logger.info("Drive search: query=%r found=%d", query, len(files))

        return {
            "status": "succeeded",
            "output": {
                "query": query,
                "count": len(files),
                "files": files,
            },
            "error": "",
        }

    except Exception as exc:
        return {"status": "failed", "output": {}, "error": f"Drive search error: {exc}"}
